### ISSUE TITLE
Add support for Integration support_urls

### ISSUE THREAD

**Issue by calebhailey** [sensu/catalog-api#20]
Add support for providing links to support/community/contribute/etc... 

```yaml
support_urls:
  - url: https://sensu.io/contact
    name: Support
  - url: https://discourse.sensu.io/c/integrations/
    name: Forum
  - url: mailto:contact@sensu.io
    name: Contact
  - url: https://github.com/sensu/catalog
    name: Contribute
```
