### ISSUE TITLE
New integrations/v1.Integration  "secret" prompt type

### ISSUE THREAD

**Issue by calebhailey** [sensu/catalog-api#55]
Add a new integrations/v1.Integration  "secret" prompt type

```yaml
---
api_version: integrations/v1
type: Integration
metadata:
  name: example
  namespace: example
spec:
  ...: ...
  prompts:
    - type: secret
      name: sumologic_url
      title: Sumo Logic Source URL
      description: Select the Sumo Logic source URL (Sensu Secret)
      required: true
      filter: "example" # (optional filter on secret names)
      env_var_fallback: true
```

Notes: 

* TBD if we should add a `env_var_fallback: true` field to allow users to add sensitive configuration as environment variables?

* variable is a hash with two keys: `secret` and `env_var`

  ```json
  {
    "secret": "",
    "env_var": ""
  }
  ```

* integrations/v1.Integrations `resource_patches` can access secret input values via `varname.secret` or `varname.env_var`
